apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-faiss
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-faiss
spec:
  storageClassName: sc-faiss
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: pvc-faiss
  gcePersistentDisk:
    pdName: k8s-faiss-storage
    fsType: ext4
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-faiss
spec:
  storageClassName: sc-faiss
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "faiss-grpc-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "faiss-grpc-server.name" . }}
    chart: {{ template "faiss-grpc-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "faiss-grpc-server.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "faiss-grpc-server.name" . }}
        release: {{ .Release.Name }}

    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.imageName }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command: ["./faiss_server", "-file_path=/data/en_wikipedia.faiss", "-nprobe=21804", "-on_cpu", "-port=8081"]

          volumeMounts:
            - name: data
              mountPath: /data
              readOnly: true

          resources:
            limits:
              nvidia.com/gpu: {{ .Values.image.numGpus }}
          
          ports:
            - containerPort: 8081
              name: grpc
            - containerPort: 8000
              name: metrics
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8081"]
            initialDelaySeconds: 1500
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8081"]
            initialDelaySeconds: 1500

      initContainers:
        - name: download
          image: jplu/gsutil:1.0.0
          command: ["gsutil", "-m", "rsync", "{{ .Values.image.bucketPath }}", "/data"]
          volumeMounts:
            - name: data
              mountPath: /data

      serviceAccountName: iden-k8s-gcs-access

      securityContext:
        runAsUser: 1000
        fsGroup: 1000

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-faiss

      nodeSelector:
        cloud.google.com/gke-nodepool: pool-faissserver

