apiVersion: v1
kind: Service
metadata:
  name: {{ template "search-orchestration.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "search-orchestration.name" . }}
    chart: {{ template "search-orchestration.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    cloud.google.com/neg: '{"ingress": false}'
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      name: http
    - port: 9000
      targetPort: metrics
      name: metrics-server
  selector:
    app: {{ template "search-orchestration.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "search-orchestration-metrics.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "search-orchestration-metrics.name" . }}
    chart: {{ template "search-orchestration.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    alpha.monitoring.coreos.com/non-namespaced: "true"
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  selector:
    app: {{ template "search-orchestration.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "search-orchestration-metrics-monitor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "search-orchestration-metrics-monitor.name" . }}
    chart: {{ template "search-orchestration.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "search-orchestration-metrics.name" . }}
  endpoints:
  - port: metrics
    interval: 15s
